name: "Priyanka Deo"
description: ""

url: "notpriya.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty

collections:
 projects:
  output: true
 gallery:
  output: true

defaults:
 - 
   scope:
    path: ""
    type: "projects"
   values:
    layout: "project"
 - 
   scope:
    path: ""
    type: "posts"
   values:
    layout: "blog_post"
    image_dir: images/blog_images

permalink: blog/:title
